language: android
dist: precise
jdk: oraclejdk8
branches:
   except:
   - l10n_alpha2
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26
before_install: 
  - chmod a+x ./scripts/deploy-*.sh
  - chmod a+x ./scripts/changelog.sh
script:
  - bash ./gradlew assembleDebug check;
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"

deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-telegram.sh
    on:
      branch: alpha
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-telegram.sh
    on:
      branch: beta
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-telegram.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-telegram.sh
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_OAUTH_TOKEN
    file: "Lawnchair-$TRAVIS_BUILD_NUMBER.apk"
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-vsmc.sh Beta
    on:
      branch: beta
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-vsmc.sh Alpha
    on:
      branch: alpha
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-vsmc.sh Release
    on:
      tags: true
